export { default as Home } from './Home'
export { default as Settings } from './Settings'
export { default as Statistics } from './Statistics'
export { default as Register } from './Register'
export { default as Login } from './Login'
